### ISSUE TITLE
Omim annotation issue : gene list not sorted

### ISSUE THREAD

**Issue by Melalaoua** [bioinfo-chru-strasbourg/howard#239] opened 2024-05-27 08:12 UTC
## Issue  
Tabix throw error that omim bed file generated from howard is not sorted (likely gene on negative strand are not correctly inserted in the bed file)

### Omim bed annotation creation
howard databases --input_extann path/to/extann --output_extann OMIMannota
tion.bed --refgene path/to/refseq.bed --genomes-folder /path/to/genome/folder --genome path/to/genome.fasta --param_extann path/to/extann_param.json

### Extann file :
{
    "OMIMannotations": {
        "reference": "hg19",
        "genes": {
            "Number": "1",
            "Type": "String",
            "Description": "Gene symbol"
        },
        "transcript": {
            "Number": "1",
            "Type": "String",
            "Description": "Refgene transcript"
        },
        "OMIM_phenotype": {
            "Number": ".",
            "Type": "String",
            "Description": "List of OMIM phenotype"
        },
        "OMIM_inheritance": {
            "Number": ".",
            "Type": "String",
            "Description": "List of OMIM inheritance"
        },
        "OMIM_ID": {
            "Number": ".",
            "Type": "Integer",
            "Description": "List of OMIM ID"
        }
    },
    "replace": {
        ",": "|",
        ";": ","
    },
    "extra_col_list": [
        "transcript"
    ],
    "transcript_extann": "",
    "mode_extann": "",
    "refgene_extann": ""
}

## For what use ?
To howard process a vcf with omim annotation
howard process --input=test.vcf --output=output.vcf --param=param.json

Param.json file : 
{
    "annotation": {
        "bcftools" : {
            "annotations" : {
                "/databases/OMIMannotations/current/hg19/sorted_OMIMannotation.all.bed.gz": {
                    "OMIM_phenotype": "OMIM_phenotype",
                    "OMIM_ID": "OMIM_ID",
                    "OMIM_inheritance" : "OMIM_inheritance"
                }
            }
        }
    }
}

## Howard version ?
main latest (07266811ffc5772cbfab790e8da0c49cea7e7e08)

@JbaptisteLam

**Comment by JbaptisteLam** [comment] 2024-09-05 10:18
Not able to reproduce the error or it's already fixed in the release

**Comment by antonylebechec** [comment] 2024-12-20 15:50
close

**Closed by antonylebechec** 2024-12-20 15:50 UTC
Labels: bug
